# Generated by Django 5.1.6 on 2025-02-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movieDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('Genre', models.CharField(blank=True, max_length=40, null=True)),
                ('Imdb', models.IntegerField(blank=True, null=True)),
                ('Review', models.CharField(blank=True, max_length=40, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Movies')),
                ('Description', models.TextField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
