# Generated by Django 5.1.6 on 2025-02-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='people/')),
            ],
        ),
        migrations.AddField(
            model_name='moviedb',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
