# Generated by Django 5.1.6 on 2025-02-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_person_moviedb_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('Desc', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='moviedb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Movies/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
