# Generated by Django 5.1.6 on 2025-02-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_genredb_alter_moviedb_image_alter_person_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedb',
            name='Review',
        ),
        migrations.AlterField(
            model_name='moviedb',
            name='Imdb',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
