# Generated by Django 5.1.6 on 2025-02-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_remove_moviedb_review_alter_moviedb_imdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedb',
            name='people',
            field=models.ManyToManyField(related_name='movies', to='AdminApp.person'),
        ),
    ]
