# Generated by Django 5.1.6 on 2025-03-12 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_moviedb_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedb',
            name='Genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='AdminApp.genredb'),
        ),
    ]
