# Generated by Django 5.1.6 on 2025-04-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_alter_moviedb_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genredb',
            name='Desc',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
