# Generated by Django 5.1.6 on 2025-02-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_UpDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=150, null=True)),
                ('Password', models.CharField(blank=True, max_length=150, null=True)),
                ('Conform_Password', models.CharField(blank=True, max_length=150, null=True)),
                ('Email', models.EmailField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
