# Generated by Django 5.1.6 on 2025-03-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_name', models.CharField(blank=True, max_length=60, null=True)),
                ('M_genre', models.CharField(blank=True, max_length=60, null=True)),
                ('M_rating', models.CharField(blank=True, max_length=60, null=True)),
                ('M_people', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
