# Generated by Django 5.1.6 on 2025-04-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='M_genre',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='M_name',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='M_people',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='M_rating',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='cast',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='movie_genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='movie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='movie_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='movie_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='my_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='my_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
