# Generated by Django 5.1.6 on 2025-04-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_remove_wishlist_m_genre_remove_wishlist_m_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='M_image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='cast',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
